### ISSUE TITLE
Smartphone app development 

### ISSUE THREAD

**Issue by MaxESP** [ictinnovaties-zorg/openwindesheart-demo#1]
hello sir, 

I am working on developing a sport app for smartphone and i would be glad to have your comment for the best way  to integrate the fonctions of the miband or any smartband directly to the smartphone app.

I'm open to any proposal

Naim

**Comment by wkeuning** [comment]
Hi MaxESP,

Thank you for your interest in the OpenWindesheart library.
The repository https://github.com/ictinnovaties-zorg/openwindesheart-demo contains an example on how to integrate the functionality of the OpenWindesheart library into an app, this should get you started on how to use this library.

Kind regards,

Wouter Keuning
Application Engineer,  Research Group IT Innovations in Health Care

Windesheim University of Applied Sciences
Faculty of Engineering // +31(0)88 469 9755 // roomnumber T5.56
Campus 2 // PO Box 10090 // 8000 GB Zwolle // +31(0)88 469 9911
www.windesheim.com/research/ict/ict-innovations-in-health-care<http://www.windesheim.com/research/ict/ict-innovations-in-health-care>

Van: MaxESP <notifications@github.com>
Verzonden: vrijdag 28 augustus 2020 17:19
Aan: ictinnovaties-zorg/openwindesheart-demo <openwindesheart-demo@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [ictinnovaties-zorg/openwindesheart-demo] Smartphone app development (#1)


hello sir,

I am working on developing a sport app for smartphone and i would be glad to have your comment for the best way to integrate the fonctions of the miband or any smartband directly to the smartphone app.

I'm open to any proposal

Naim
